name: Deploy payment-gateway-service to oxium-server-1

on:
  push:
    paths:
      - "payment-gateway-service/**" 
    branches:
      - staging

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID}}
      ECR_REPOSITORY: payment-gateway-microservice
      IMAGE_TAG: latest
      CONTAINER_NAME: payment-gateway-container
      SERVICE_NAME: payment-gateway-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        id: build-and-push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: payment-gateway-microservice
          IMAGE_TAG: latest
          SERVICE_NAME: payment-gateway-service

        run: |
      
          cd ${{env.SERVICE_NAME}} && docker build -t ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID}}
          SSH_KEY: ${{ secrets.OCPP_NEW_PEM }}
          EC2_INSTANCE_IP:  ${{ secrets.OCPP_EC2_INSTANCE_1}}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: payment-gateway-microservice
          IMAGE_TAG: latest
          AWS_LOGS_GROUP: OxiumPaymentGatewayLogs
          USERNAME: ubuntu
          CONTAINER_NAME: payment-gateway-container
          PORT: 6684

        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY}}

          script: |

            # Refresh ECR login
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
           
            # Pull Docker Image
            sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

            sudo docker stop ${{ env.CONTAINER_NAME }} || true
            sudo docker rm ${{ env.CONTAINER_NAME }} || true

            sudo docker run -d \
              -p ${{ env.PORT }}:${{ env.PORT }}\
              --name ${{ env.CONTAINER_NAME }} \
              --log-driver=awslogs \
              --log-opt awslogs-region=${{ env.AWS_REGION }} \
              --log-opt awslogs-group=${{ env.AWS_LOGS_GROUP }} \
              -e ENVIRONMENT=production \
               ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

            
    
          